version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=s3
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - '4566:4566'
      - '4572:4572'
    volumes:
      - ./localstack-data:/var/lib/localstack  # Persistent data
      - /var/run/docker.sock:/var/run/docker.sock  # Required for Lambda and other services
